CONTRIBUTING.md & README.md starting points
zatech/wiki pull request #4
Opened 2020-10-10 12:58 UTC by n1c

2020-10-10 23:00 UTC, JohnRoux requested changes
Keeping the brand name consistent & minor changes

2020-10-10 23:00 UTC, JohnRoux commented on CONTRIBUTING.md
> +Thanks for taking an interest in contributing to the ZATech Wiki! For starters, make sure you're already familar with the group's [Code of Conduct](https://github.com/zatech/code-of-conduct).
```suggestion
Thanks for taking an interest in contributing to the ZA Tech Wiki! For starters, make sure you're already familiar with the group's [Code of Conduct](https://github.com/zatech/code-of-conduct).
```

2020-10-12 11:40 UTC, JohnRoux approved these changes

2020-10-15 09:43 UTC, zoidbergwill approved these changes

2020-10-15 10:09 UTC, sixhobbits approved these changes

2020-10-15 10:41 UTC, merged