add freelance jobposting
zatech/wiki pull request #5
Opened 2020-10-28 14:59 UTC by sixhobbits

add freelance job post faq

2020-10-28 23:15 UTC, JohnRoux reviewed
Looks pretty solid 👍

2020-10-28 23:15 UTC, JohnRoux commented on faqs/howtojobpost-freelance.markdown
> +Once the form has been submitted a request will be sent to the admins for approval.
"to an approval team"

2020-10-29 08:21 UTC, JohnRoux requested changes
Added Suggestion

2020-10-29 08:21 UTC, JohnRoux commented on faqs/howtojobpost-freelance.markdown
> +Once the form has been submitted a request will be sent to the admins for approval.
```suggestion
Once the form has been submitted a request will be sent to the approval team.
```

2020-11-02 12:42 UTC, sixhobbits commented
made the same change in the one I copied it from.

2020-11-02 14:58 UTC, n1c approved these changes

2020-11-02 15:17 UTC, JohnRoux approved these changes

2020-11-03 13:52 UTC, merged